monounity/karma-typescript

- README.md
- example-project/karma.conf.js
- lib/preprocessor.js
Fixes #15.
Without this flag, when you are debugging your tests and try to step into code from some non-spec file, you get code instrumented by Istanbul instead of the original TypeScript.
This problem does not occur when stepping into code from *.spec files as they are already excluded from Istanbul instrumentation.
> Added flag disableCodeCoverageInstrumentation

- README.md
I've spent a day trying to figure this out and experimenting with webpack based solutions.  I'd recommend adding a bit more to the minimal configuration displayed in the readme.  
Two things:
The a number of the webpack solutions required that all the source and test files get bundled into a single entry point.  As I understand, this does not as one would not necessarily want coverage run on the tests themselves.  To this end, I added a second entry in the files array to distinguish test and source resources.  
In the preprocessors sections, I added coverage to source resources but not to the test resources.  I discovered that this needed to be done to produce the output only by stumbling accross the issue discussion in the repo.  I think a more prominent location in the readme would …
> add more description to minimal configuration in readme

- dist/bundler/transformer.js
- src/api/transforms.ts
- src/bundler/transformer.ts
see https://github.com/monounity/karma-typescript/issues/152
> Add possibility to apply comments for coverage settings in transforms 

- .npmignore
- README.md
- examples/angular2/package.json
- examples/angularjs/package.json
- examples/docker/package.json
- examples/gulp/package.json
- examples/mocha/package.json
- examples/typescript-1.6.2/package.json
- examples/typescript-latest/package.json
- package.json
- tests/integration-1.8.10/package.json
- tests/integration-latest/bower.json
- tests/integration-latest/package.json
This reduces bundle size by ~17MB. Mostly because of `x-performance`.
> Removed tests from NPM

- .travis.yml
- appveyor.yml
- ci/install.bat
- ci/install.sh
`npm@3`, which is the version of `npm` for NodeJS stable, does not automatically run `prepare` before install. Therefore, it must be manually invoked for `integration-latest`, otherwise bower components won't be set up
> Manually run 'prepare' script in integration-latest test directory

- package.json
Note that [karma-babel-preprocesser](https://github.com/babel/karma-babel-preprocessor/blob/master/package.json#L31) uses `peerDepenencies` to show that it _does_ depend on certain libraries, but it wants the dependent project to define the dependencies.
This PR applies the same philosophy to `karma-typescript`, with the understanding that we can't (err, shouldn't :wink:) hardcode our `typescript` and `karma` dependencies
> Adds karma and typescript as peer dependencies

- package.json
Relates to https://github.com/jashkenas/coffeescript/issues/4805
pad update to the latest coffeescript and released a major version
This is breaking a lot of windows users
Closes: #221
> fix: karma-typescript fails on npm install command 

- src/api/transforms.ts
- src/bundler/bundle-item.ts
- src/bundler/transformer.ts
Fixes #217 
This PR adds a new callback parameter to transformers: `transpile`. 
When set to true by transformer, `bundleItem` is then considered as a normal script rather than just contents. This means that the bundler will process its dependencies and include them, so you can `require()` to your heart's contents.
There is no compatibility issue since this is a new parameter and when it's not set the code behaves exactly like before.
**BIG GOTCHA** 
`karma-typescript` never compiles the `source` into `ast` after transformers are run. 
As can be seen in the code, it expects transformers to provide their own AST:
https://github.com/monounity/karma-typescript/blob/master/src/bundler/transformer.ts#L89
So in order for the new option to effectively work, transformer has to do this:
```js …
```
> Support processing JS produced by transformers.

- package.json
Fixes the following warning:
> npm WARN karma-typescript@3.0.9 requires a peer of karma@1 but none is installed. You must install peer dependencies yourself.
> Allow Karma@2 in peerDependencies

- package.json
- src/api/transforms.ts
- src/shared/configuration.ts
- tests/integration-latest/package.json
- tests/integration-latest/src/typescript/compiler-paths/compiler-paths-tester.ts
Updated log4js to the latest as this is the version, which karma@3.0.0 uses.
Changes to logging configuration is to account for the corrected `karma` type definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29386
> Added support for karma 3.x and typescript 3.x

- src/bundler/bundle-item.ts
- tests/integration-latest/src/imports/json-import/json-direct-import.ts
- tests/integration-latest/src/imports/json-import/json-import-tester.spec.ts
- tests/integration-latest/src/imports/json-import/json-import-tester.ts
- tests/integration-latest/tsconfig.json
Allows for direct imports of json into typescript.
Fixes #291.
TODO: Typescript will automatically resolve typings of the imported json (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---resolvejsonmodule). How do I add a test to ensure that TS complains if I use the imported data incorrectly?
> Add support for resolveJsonModule

- .gitignore
- packages/karma-typescript/src/bundler/resolve/resolver.ts
This adds an additional guard to the resolver, preventing npm modules that include their original typescript sources from being recognised as part of the current project.
> Fix #319: external npm modules must not become bundle items

- packages/karma-typescript-postcss-transform/src/transform.spec.ts
- packages/karma-typescript/src/client/commonjs.ts
- packages/karma-typescript/src/compiler/compiler.ts
TypeScript 3.0 added support for [project references](https://www.typescriptlang.org/docs/handbook/project-references.html), allowing for quickly building large projects. A list of project references is provided by `ts.parseJsonConfigFileContent`, which is assigned to `tsconfig` at `compiler.ts`. The property is `projectReferences`.
The property value should be passed to `ts.createProgram` by using a new signature that supports projectReferences. This PR implements the requirement, allowing for the usage of project references alongside karma-typescript.
> Fix project references

- packages/karma-typescript-postcss-transform/src/transform.spec.ts
- packages/karma-typescript/README.md
- packages/karma-typescript/src/api/configuration.ts
- packages/karma-typescript/src/compiler/compiler.ts
- packages/karma-typescript/src/shared/configuration.ts
Fix #274 by introducing a new variable called stopOnFailure (default true) which allows tests to be run when typescript compile errors are present.
> Stop on compile error

- packages/karma-typescript/src/karma/reporter.ts
I've investigated a bit what the differences were between `4.1.1` and `5.x.y`, I noticed that the package was previously doing `sync` operations.
Since `5.0.0` the coverage calculations are done via the `istanbul-lib-coverage` package to process the results.
The issue here is that the processing is now async and mutation of the `results.exitCode` property is now part of a `microTask`.
The only solution I could find was to aggregate all of the threshold checks and actually exit once all of the checks are performed.
fix #376
> fix: exit if the coverage threshold is not met

- packages/karma-typescript/package.json
To avoid warnings and make installations work with npm v7 without errors.
> Add Typescript v4 as allowed peerDependency

- packages/karma-typescript/src/karma/reporter.ts
@erikbarke your question in the previous PR stuck with me a bit, this is my attempt at an alternative (hopefully more readable/intuitive approach).
This PR is completely *optional*.
> fix / improve readability of coverage check logic

- packages/karma-typescript/README.md
- packages/karma-typescript/src/api/configuration.ts
- packages/karma-typescript/src/karma/reporter.ts
> Custom Watermark Thresholds

- packages/karma-typescript/src/karma/reporter.ts
When running Karma with autowatch enabled, the process will exit if coverage thresholds aren't met. This conditional just ensures singleRun is enabled before killing the process.
Fixes https://github.com/monounity/karma-typescript/issues/415
> Don't kill process when coverage threshold isn't met if singleRun is false

- README.md
- examples/angular2/package.json
- examples/angularjs/package.json
- examples/docker/package.json
- examples/mocha/package.json
- examples/typescript-1.6.2/package.json
- examples/typescript-1.8.10/package.json
- examples/typescript-latest/package.json
- packages/karma-typescript-angular2-transform/package.json
- packages/karma-typescript-cssmodules-transform/package.json
- packages/karma-typescript-es6-transform/package.json
- packages/karma-typescript-es6-transform/src/transform.ts
- packages/karma-typescript-postcss-transform/package.json
- packages/karma-typescript/README.md
- packages/karma-typescript/package.json
- packages/karma-typescript/src/bundler/validator.ts
- tests/integration-latest/package.json
- updates peer dependencies mark to support `karma` v6
- update `karma` dependency to `6.1.0`
- update `@types/karma` to `6.1.0`
`karma` 6.1.0 is breaking (kind of), mostly for Dart users. Should not have direct impact on Karma TS integration, but peer dependency definiiton makes using v6 impossible. Hence this change.
Tested locally, changes applied and tested in all packages, except of:
- Docker (requires app rewrite, it fails at runtime due to yars/args error)
- Gulp plugin (I cannot take a dent on how it works)
Thanks!
Update acorn.parse usage to support `ecmaVersion`
Opted to `lastest`, the reasoning is TS is defined as `lastest`.
Fixes #409
[README] bump copy year and minor cleanup
> Update peer dependency to support `karma` 6

- examples/angular2/package.json
- examples/angular2/src/app/hello.ts
- packages/karma-typescript/src/bundler/bundle-item.ts
- packages/karma-typescript/src/bundler/dependency-walker.ts
- packages/karma-typescript/src/bundler/resolve/resolver.ts
<del>I'm not sure if this is a valid fix since the test passed locally on my laptop failed on CI.</del>
Please make a review.
Fix #408
> Fix import .d.ts as dependency

- packages/karma-typescript/src/karma/reporter.ts
Situation:
I want to output everything in `./coverage` this cannot be easily achieve at the moment. If the `subdirectory` is set to `''`, it will fallback to the browser-name value.
Alternative:
At the moment I'm doing the following to achieve the desired result on my project: 
```
'html': {
'directory': 'coverage',
'subdirectory': () => '',
},
'lcovonly': {
'directory': 'coverage',
'subdirectory': () => '',
},
```
Solution:
Use nullish, this way the defaults will be used only when the values are `undefined` or `null`.
> fix: use nullish coalescing for coverage directory paths

- packages/karma-typescript-angular2-transform/package-lock.json
- packages/karma-typescript-angular2-transform/package.json
- packages/karma-typescript-es6-transform/package-lock.json
- packages/karma-typescript-es6-transform/package.json
- packages/karma-typescript/package-lock.json
- packages/karma-typescript/package.json
- tests/integration-latest/package.json
In version [8.0.3](https://github.com/acornjs/acorn/blob/2cceb5ec3aeb98b2dd6958106709d97aa8ab0c04/acorn/CHANGELOG.md#803-2020-10-02):
`Fix a wasteful loop during Parser creation when setting ecmaVersion to "latest".`
> chore: upgrade to acorn@8.1.0 

- packages/karma-typescript/src/bundler/dependency-walker.ts
https://github.com/microsoft/TypeScript/blob/1cee9731d22c7a1f97ac957cb89d8664cadc4717/src/compiler/moduleNameResolver.ts#L660
fixes #499
> Dependency walker map checking supports new TS ModeAwareCache

- packages/karma-typescript/README.md
This adds documentation for the `acornOptions` configuration key under `bundlerOptions`, addressing previous issues such as #255  and #520.
> Add documentation update for acornOptions
